### ISSUE TITLE
Create people detection tutorial

### ISSUE THREAD

**Issue by edgarriba** [farm-ng/amiga-dev-kit#146]
after merging https://github.com/farm-ng/farm-ng-amiga/pull/75

- create a tutorial similar to https://amiga.farm-ng.com/docs/examples/camera_client/
  - describe how to create a custom service/client
- create a kivy app implementing the service directly in the robot after the service is integrated
  - make a video tutorial for youtube

**Comment by Hackerman342** [comment]
Outstanding is to test on Mac + resolve any issues running on MAc (cc @jerrycowell96 @HavivaB )
