### ISSUE TITLE
Robot access tutorials

### ISSUE THREAD

**Issue by Hackerman342** [farm-ng/amiga-dev-kit#201]
The basic idea here is to translate Tony's docs in SEP to public facing documentation for accessing and interacting with the new Amiga brain OS

- ssh config
- fleets account
- VS Code set up
- etc.

**Comment by guilhermedemouraa** [comment]
Closing this issue as completed in https://github.com/farm-ng/amiga-dev-kit/pull/206

**Comment by guilhermedemouraa** [comment]
Closing this issue as completed in https://github.com/farm-ng/amiga-dev-kit/pull/206
