### ISSUE TITLE
Service Client example missing files

### ISSUE THREAD

**Issue by Hackerman342** [farm-ng/amiga-dev-kit#273]
# 📚 Documentation Issue

Reported by user https://discourse.farm-ng.com/u/gsainsbury86 in discourse thread: https://discourse.farm-ng.com/t/getting-started-with-brain-adk-and-additional-sensors/290/5

> I got a bit stuck today. When trying to run the example Service Client demo, I got an error about not being able to find the two_ints_pb2 module. Reading the documentation, it says that these were the included protocolbuf files, but we could regenerate them with genprotos.py. I couldn’t find the original files or the genprotos script. After some reading, I found that I could generate the file using protoc --python_out=. two_ints.proto . Just a note in case anyone else gets stuck.
> 
> After that, I was able to define a new protobuf file for image_data passing and get a minimal example working where I pass an existing image between a client and service.

**[Service Client Example](https://amiga.farm-ng.com/docs/examples/service_client/)** is missing `two_ints_pb2.py`, `two_ints_pb2.pyi`, &  `genprotos.py`

**Comment by Hackerman342** [comment]
@edgarriba maybe these were omitted by the `.gitignore`?I looked around in `farm-ng-amiga` & `farm-ng-core` for `genprotos.py` and did not find it

**Comment by edgarriba** [comment]
fixed https://github.com/farm-ng/farm-ng-amiga/pull/176
