### ISSUE TITLE
Major documentation overhaul for AmigaOS v2.3 release

### ISSUE THREAD

**Issue by Hackerman342** [farm-ng/amiga-dev-kit#290]
Update instructions for the new apps and services and logging etc. A lot of changes in this release

**Comment by AgustinBRodriguez** [comment]
Document with proposed changes and related tasks.
https://docs.google.com/document/d/1WdwjCtmAWtWJJAzj2dvB-_Po3O2aJ7jWK2gY2BJBiEI/edit?usp=sharing

**Comment by Hackerman342** [comment]
Started in:
- https://github.com/farm-ng/amiga-dev-kit/pull/296

**Comment by guilhermedemouraa** [comment]
Closed as completed on https://github.com/farm-ng/amiga-dev-kit/pull/306
