### ISSUE TITLE
Documentation of control states / interaction

### ISSUE THREAD

**Issue by TravisJoe** [farm-ng/amiga-dev-kit#44]
Overview of the controls, states, and general best practices for manual mode controls of the Amiga.

**Comment by Hackerman342** [comment]
I'll take this one.
I understand the desire is for documentation of the control states and how the nodes (dashboard, pedant, brain, and sdk) are intended to interact.

**Comment by Hackerman342** [comment]
Reopening, as the docusaurus deploy did not generate the mermaid formatted flow chart

**Comment by Hackerman342** [comment]
Fixed with #47 & [67289af](https://github.com/farm-ng/amiga-dev-kit/commit/67289af38f92f12b90c72385c416cafb362e8992)
