### ISSUE TITLE
hello world virtual joystick with camera template repository

### ISSUE THREAD

**Issue by ethanrublee** [farm-ng/amiga-dev-kit#52]
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

Allow users to create an application for the Amiga brain easily.

Folder structure:

- setup.cfg - requires amiga-brain-api
- setup.py
- project.toml
- apps/
  - simple_virtual_joystick
       - grabs frames from oak service and commands base over canbus service
- services/

**Comment by edgarriba** [comment]
we could probably try to enforce users to have a test directory to check at the very least that package generation is alright and some basic functionality. Otherwise, this could easily lead to poor and low tested package ecosystem.

**Comment by Hackerman342** [comment]
This has been completed! See https://github.com/farm-ng/amiga-brain-example
