### ISSUE TITLE
[docs] Updated debug / service cable notes

### ISSUE THREAD

**Issue by Hackerman342** [farm-ng/amiga-dev-kit#65]
We should update the descriptions on https://amiga.farm-ng.com/docs/debug_cable/ with the new debug cable and service cable.

- [ ] Description / distinguish between the two
- [ ] Pictures
- [ ] How to connect

**Comment by jerrycowell96** [comment]
Received. Work in progress!

**Comment by jerrycowell96** [comment]
I made a commit that added the service cable page and update debug overview page

**Comment by ethanrublee** [comment]
Suggest adding link to commit, or pr when referring to it in issues.
