### ISSUE TITLE
[docs] Support page

### ISSUE THREAD

**Issue by Hackerman342** [farm-ng/amiga-dev-kit#68]
@jerrycowell96 We want documented instructions for dev kit users to open a git issue in amiga-dev-kit.

This should be distinct from the issues / ticketing pipeline for production where users of the amiga in the field can submit crash / failure reports and feature requests (cc @TravisJoe @christopherbradski ). Though we will also want docs on how to do that once the system is in place.

**Comment by edgarriba** [comment]
That tutorial should point to: https://github.com/farm-ng/amiga-dev-kit/issues/new/choose
In addition, add issue template -> https://github.com/kornia/kornia/tree/master/.github/ISSUE_TEMPLATE

**Comment by Hackerman342** [comment]
Agreed with @edgarriba above for the issues

What we should do is:

- [ ] Add a support page
- [ ] Differentiate when to use git issues / discord / (coming soon) tickets

While we're at it:

- [ ] Update `Contribute` page to explain how to add a page to the tab (sidebars) or top

**Comment by jerrycowell96** [comment]
Sure thing I will start on this soon

**Comment by Hackerman342** [comment]
Completed with #96
