### ISSUE TITLE
[docs] Remove references of `brain` and `amiga-brain-api`

### ISSUE THREAD

**Issue by Hackerman342** [farm-ng/amiga-dev-kit#79]
- [ ] Update submodule to `farm-ng-amiga`
- [ ] Replace `cd brain/` or `cd amiga-brain-api/` with `cd farm-ng-amiga/` in docs
  - [ ] Also check the `farm-ng-amiga` README's
- [ ] Update all links to reflect `farm-ng-amiga` (could be `brain` or `amiga-brain-api`)

**Comment by jerrycowell96** [comment]
I'm not sure if these changes have been made already but I'm searching for the changes and aren't finding them.

**Comment by Hackerman342** [comment]
Oh yeah, done with #80
