### ISSUE TITLE
[docs] pendant page

### ISSUE THREAD

**Issue by Hackerman342** [farm-ng/amiga-dev-kit#88]

**Comment by jerrycowell96** [comment]
Should this page include these items:

- [ ] what is the pendant 
- [ ] first steps
- [ ] how to calibrate
- [ ] photo of pendant

**Comment by Hackerman342** [comment]
Also:

- [ ] How to flash
- [ ] Text / Shape button mappings 
- [ ] Button functions
- [ ] Basic troubleshooting (can be on FAQ page)
